- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.7.0
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.7.0?classifier=sources
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.7.1
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.7.1?classifier=sources
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.8.0
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.8.0?classifier=sources
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.8.1
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.8.1?classifier=sources
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.9.0
- pkg:maven/org.codelibs.elasticsearch.module/tasks@7.9.0?classifier=sources
