- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@0.6.0
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@0.6.0?classifier=sources
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@0.6.1
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@0.6.1?classifier=sources
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.0
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.0?classifier=sources
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.1
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.1?classifier=sources
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.2
- pkg:maven/io.github.jyllands-posten/play-prometheus-filters_2.13@1.0.2?classifier=sources
