- pkg:maven/hu.webarticum.holodb/config@0.5.0?classifier=sources
- pkg:maven/hu.webarticum.holodb/config@0.6.0?classifier=sources
- pkg:maven/hu.webarticum.holodb/config@0.7.0?classifier=sources
- pkg:maven/hu.webarticum.holodb/config@0.7.1?classifier=sources
