- pkg:maven/com.github.fmjsjx/libcommon-prometheus-client@3.7.0-RC1?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus-client@3.7.0?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus-client@3.8.0-RC1?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus-client@3.8.0?classifier=sources
- pkg:maven/com.github.fmjsjx/libcommon-prometheus-client@3.8.1?classifier=sources
