- pkg:maven/org.apache.ozhera/prometheus-diy-starter@2.2.2-incubating
- pkg:maven/org.apache.ozhera/prometheus-diy-starter@2.2.2-incubating?classifier=sources
- pkg:maven/org.apache.ozhera/prometheus-diy-starter@2.2.3-incubating
- pkg:maven/org.apache.ozhera/prometheus-diy-starter@2.2.3-incubating?classifier=sources
