- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.22.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.23.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.24.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.25.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.25.1-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.26.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.27.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.28.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.29.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.30.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.31.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.32.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.33.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.34.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.35.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.36.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.37.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.38.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.39.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.40.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.41.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.42.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.43.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.44.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.45.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.46.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.47.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.48.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.49.0-alpha?classifier=sources
