- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.22.0-alpha?classifier=sources
- pkg:maven/io.opentelemetry.contrib/opentelemetry-prometheus-client-bridge@1.23.0-alpha?classifier=sources
